routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Category;
use App\PointOfSale;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin', function () {
    return view('admin/index');
})->name('admin');


Route::get('/categories/{id}/delete', 'CategoryController@destroy')->name('categories.delete');
Route::resource('categories', 'CategoryController');

Route::get('/colors/{id}/delete', 'ColorController@destroy')->name('colors.delete');
Route::resource('colors', 'ColorController');
Route::post('/colors/search', 'CategoryController@search')->name('colors.search');

Route::get('/pointsofsale/{id}/delete', 'PointOfSaleController@destroy')->name('pointsofsale.delete');
Route::resource('pointsofsale','PointOfSaleController');
Route::post('/pointsofsale/search', 'PointOfSaleController@search')->name('pointsofsale.search');


Route::resource('offers', 'OfferController');
Route::resource('products', 'ProductController');
Route::resource('subcategories', 'SubcategoryController');

// Route::get('/hipoalergenicos', 'ColorController@showHipo');




View::composer('*', function ($view) {
    $categories = Category::all();
    $view->with('categories', $categories);
});

View::composer(['layouts.app', 'categories.puntos de venta'], function ($view) {
    $pointsOfSale = PointOfSale::all();
    $view->with('pointsOfSale', $pointsOfSale);
});

View::composer('categories.puntos de venta', function ($view) {
    $pointsOfSale = PointOfSale::all();
    $view->with('pointsOfSale', $pointsOfSale);
});

Route::get('/seccion/esmalte/{id}', 'PageController@categoryView')->name('esmalte');

resources/views/admin/pointsofsale/create.blade.php
@extends('layouts.app')
@section('content')
<div class="col-12">
    <div class="col-12 text-center mb-5">
        <h2>Nuevo punto de venta</h2>
    </div>
    <form class="col-12 mx-auto" action="{{route('pointsofsale.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-row">
            <div id="div-name" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Nombre</label></h4>
                <input name="name" class="form-control" type="text" value="{{ old('name') }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Nombre del punto de venta</b></small>
                @error('name')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="div-address" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Direccion</label></h4>
                <input name="address" class="form-control" type="text" value="{{ old('address') }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Direccion del punto de venta</b></small>
                @error('address')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="div-link" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Link del mapa</label></h4>
                <input name="link" class="form-control" type="text" value="{{ old('link') }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Link extraido de maps</b></small>
                @error('link')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="div-authorized" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Autorizado</label></h4>
                 <div class="form-check">
                    <label for="">si</label>
                    <input name="authorized" class="mt-1 mr-1" type="checkbox" value="si">
                </div>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Marcar este campo solo si el punto de venta es agente autorizado</b></small>
                @error('authorized')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
        </div>
        <div id="buttons" class="text-center col-12">
            <button class="mx-2 btn btn-outline-dark" type="submit">Agregar</button>
            <a href="{{route('pointsofsale.index')}}"><button class="btn btn-outline-dark" type="button">Cancelar</button></a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/pointsofsale/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="col-12">
    <div class="col-12 text-center mb-5">
        <h2>Nuevo punto de venta</h2>
    </div>
    <form class="col-12 mx-auto" action="{{route('pointsofsale.update',['pointsofsale'=>$pointOfSale])}}" method="post" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="form-row">
            <div id="div-name" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Nombre</label></h4>
                <input name="name" class="form-control" type="text" value="{{ $pointOfSale->name }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Nombre del punto de venta</b></small>
                @error('name')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="div-address" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Direccion</label></h4>
                <input name="address" class="form-control" type="text" value="{{ $pointOfSale->address }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Direccion del punto de venta</b></small>
                @error('address')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="div-link" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Link del mapa</label></h4>
                <input name="link" class="form-control" type="text" value="{{ $pointOfSale->link }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Link extraido de maps</b></small>
                @error('link')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="div-authorized" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Autorizado</label></h4>
                 <div class="form-check">
                    @if($pointOfSale->authorized)
                    <label for="">si</label>
                    <input name="authorized" class="mt-1 mr-1" type="checkbox" checked value="si">
                    @else
                    <label for="">si</label>
                    <input name="authorized" class="mt-1 mr-1" type="checkbox" value="si">
                    @endif
                </div>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Marcar este campo solo si el punto de venta es agente autorizado</b></small>
                @error('authorized')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
        </div>
        <div id="buttons" class="text-center col-12">
            <button class="mx-2 btn btn-outline-dark" type="submit">Modificar</button>
            <a href="{{route('pointsofsale.index')}}"><button class="btn btn-outline-dark" type="button">Cancelar</button></a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/pointsofsale/index.blade.php
@extends('layouts.app')
@section('content')
<div id="div-all-pos" class="col-12">
    <div id="div-tit-pos" class="mx-auto text-center col-12">
        <h2>Puntos de venta</h2>
        <a href="{{route('admin')}}" style="text-decoration: none; color:black"><i class="fas fa-arrow-circle-left"></i> Volver</a>
    </div>
    <div id="div-opc-pos" class="row justify-content-center mx-auto mb-3 col-12 col-md-8 col-lg-6 col-xl-4">
        <div class="my-3 col-6 col-md-4">
            <a href="{{route('pointsofsale.create')}}"><button class="btn btn-outline-dark w-100">Nuevo</button></a>
        </div>
        <form class="input-group input-group-sm mb-5 my-auto col-12 col-md-6" action="{{route('pointsofsale.search')}}" method="post">
            @csrf
            <div class="input-group-prepend">
                <button class="input-group-text" id="inputGroup-sizing-sm">Buscar</button>
            </div>
            <input type="text" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
        </form>
    </div>
    <div class="my-2 col-12 text-center">
        @if(Session::has('notice'))
        <h3 class="my-auto text-success"><strong>{{ Session::get('notice') }}</strong></h3>
        @endif
    </div>
</div>
<div class="table" style="overflow-x:auto;">
    <table class="mx-auto">
        <thead>
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Direccion</th>
                <th scope="col">Autorizado</th>
                <th scope="col">Opciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($pointsOfSale as $pointOfsale => $data)
            <tr>
                <th scope="row">{{$data->id}}</th>
                <th>{{$data->name}}</th>
                <th>{{$data->address}}</th>
                @if ($data->authorized)
                    <th class="text-center">Si</th>
                @else
                    <th class="text-center">No</th>
                @endif
               <th>
                    <a href="{{route('pointsofsale.edit',['pointsofsale'=>$data])}}">editar</a>
                    ||
                    <a href="{{route('pointsofsale.delete',['id'=>$data])}}">eliminar</a>
                </th>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection