routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Category;
use App\PointOfSale;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin', function () {
    return view('admin/index');
})->name('admin');


Route::get('/categories/{id}/delete', 'CategoryController@destroy')->name('categories.delete');
Route::resource('categories', 'CategoryController');

Route::get('/colors/{id}/delete', 'ColorController@destroy')->name('colors.delete');
Route::resource('colors', 'ColorController');
Route::post('/colors/search', 'CategoryController@search')->name('colors.search');

Route::get('/pointsofsale/{id}/delete', 'PointOfSaleController@destroy')->name('pointsofsale.delete');
Route::resource('pointsofsale','PointOfSaleController');
Route::post('/pointsofsale/search', 'PointOfSaleController@search')->name('pointsofsale.search');


Route::resource('offers', 'OfferController');
Route::resource('products', 'ProductController');
Route::resource('subcategories', 'SubcategoryController');

// Route::get('/hipoalergenicos', 'ColorController@showHipo');




View::composer('*', function ($view) {
    $categories = Category::all();
    $view->with('categories', $categories);
});

View::composer(['layouts.app', 'categories.puntos de venta'], function ($view) {
    $pointsOfSale = PointOfSale::all();
    $view->with('pointsOfSale', $pointsOfSale);
});

View::composer('categories.puntos de venta', function ($view) {
    $pointsOfSale = PointOfSale::all();
    $view->with('pointsOfSale', $pointsOfSale);
});

Route::get('/seccion/esmalte/{id}', 'PageController@categoryView')->name('esmalte');

app/Color.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    public $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
}

app/Http/Controllers/ColorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Color;
use App\Category;


class ColorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $colors = Color::all();
        $vac = compact('colors');
        return view('admin.color.index', $vac);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $vac = compact('categories',);
        return view('admin.color.create', $vac);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $season = false;

        if (isset($request['season'])) {
            $season = true;
        }

        $image = $this->createImage($request);
        Color::create([
            'name' => $request['name'],
            'hexadecimal' => $request['hexadecimal'],
            'code' => $request['code'],
            'category_id' => $request['category'],
            'image'=>$image,
            'season'=> $season,
        ]);

        return redirect()->route('colors.index')->with('notice', 'El color '. $request['code'] .' ha sido creado correctamente.');
    }

    // /**
    //  * Display the specified resource.
    //  *
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    // public function show($id)
    // {
    //     //
    // }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $color = Color::find($id);
        $categories = Category::all();
        $vac = compact('color', 'categories',);
        return view('admin.color.edit', $vac);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $color = Color::find($id);

        $name = $color->name;
        if (isset($request['name'])) {
            $name = $request['name'];
        }

        $category = $color->category_id;
        if (isset($request['category'])) {
            $category = $request['category'];
        }

        $hexadecimal = $color->hexadecimal;
        if (isset($request['hexadecimal'])) {
            $hexadecimal = $request['hexadecimal'];
        }

        $code = $color->code;
        if (isset($request['code'])) {
            $code = $request['code'];
        }

        $image = $color->image;
        if (isset($request['image'])) {
            $image = $this->createImage($request);
        }

        $season = false;
        
        if (isset($request['season'])) {
            $season = true;
        }

        $color->update([
            'name' => $name,
            'category_id' => $category,
            'hexadecimal' => $hexadecimal,
            'code' => $code,
            'image'=>$image,
            'season'=>$season,
        ]);

        return redirect()->route('colors.index')->with('notice', 'El color ha sido editado correctamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $color = Color::find($id);
        $color->delete();
        return redirect()->route('colors.index')->with('notice', 'El color ha sido eliminado correctamente.');
    }

    /**
     * @param  null|Request
     */
    public function search(Request $req)
    {
        if ($req['buscador']) {
            $colors = Color::where('name', "like", "%" . $req['buscador'] . "%")->get();
            $vac = compact('colors');
            return view('admin.color.results', $vac);
        }

        $colors = Color::all();
        $vac = compact('colors');
        return view('admin.color.results', $vac);
    }
    
    public function validator(Request $request)
    {
        $rules = [
            'name' => 'required||string|max:50',
            'code' =>  'required|unique:colors|string|max:6',
        ];
        $message = [
            'required' => 'El campo es obligatorio.',
            'unique' => 'El color ya existe en nuestra base.',
            'string' => 'Solo se admiten letras.',
            'max' => 'El campo debe tener menos de :max carateres.',
        ];
        return $this->validate($request, $rules, $message);
    }

    public function createImage(Request $request)
    {
        $file = $request['image'];
        $name = $request->input('code') . "." . $file->extension();
        $path = $file->storeAs('colors', $name, 'public');
        
        return $path;
    }
}

resources/views/admin/color/create.blade.php
@extends('layouts.app')
@section('content')
<div class="col-12">
    <div class="col-12 text-center mb-5">
        <h2>Nuevo Color</h2>
    </div>
    <form class="col-12 mx-auto" action="{{route('colors.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-row">
            <div id="category" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Categoria</label></h4>
                <select class="form-control mb-1" name="category" value="{{ old('category') }}" id="">
                    <option value="">Elija una categoria</option>
                    @if(isset($categories))
                        @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                        @endforeach
                    @endif
                </select>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Categoria a la que pertenece el color</b></small>
                <a href="{{route('categories.create')}}"><button class="btn btn-outline-dark" type="button">Agregar Categoria</button></a>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Si no encuentra la categoria en el listado, agreguela</b></small>
                @error('category_id')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="div-code" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Codigo</label></h4>
                <input name="code" class="form-control" type="text" value="{{ old('code') }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Codigo del color</b></small>
                @error('code')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="hexadecimal" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Valor Hexadecimal</label></h4>
                <input name="hexadecimal" class="form-control" type="text" value="#{{ old('hexadecimal') }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Codigo del valor hexadecimal</b></small>
                @error('code')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="div-image" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Imagen</label></h4>
                <input name="image" class="form-control-file" type="file">
                @error('image')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="extras" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Extras</label></h4>
                <div class="form-check">
                    <input name="season" class="mt-1 mr-1" type="checkbox" value="si">
                    <label for="">Color de temporada</label>
                </div>
            </div>
        </div>
        <div id="buttons" class="text-center col-12">
            <button class="mx-2 btn btn-outline-dark" type="submit">Agregar</button>
            <a href="{{route('colors.index')}}"><button class="btn btn-outline-dark" type="button">Cancelar</button></a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/color/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="col-12">
    <div class="col-12 text-center mb-5">
        <h2>Modificar Color</h2>
    </div>
    <form class="col-12 mx-auto" action="{{route('colors.update',['color'=>$color])}}" method="post" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="form-row">
             {{-- <div id="div-color" class="form-group col-12 col-md-6 col-lg-1">
                <h4><label for="">Color</label></h4>
                <input class="" id="input-color" name="hexadecimal" type="color" value="{{ $color->hexadecimal}}">
                @error('color')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div> --}}
            <div id="category" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Categoria</label></h4>
                <select class="form-control mb-1" name="category" value="{{ $color->category->name }}" id="">
                    <option value="">Elija una categoria</option>
                    @foreach($categories as $category)
                    <option <?php if ($category->id == $color->category_id) echo "selected"; ?> value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Categoria a la que pertenece el color</b></small>
                <a href="{{route('categories.create')}}"><button class="btn btn-outline-dark" type="button">Agregar Categoria</button></a>
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Si no encuentra la categoria en el listado, agreguela</b></small>
                @error('category_id')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="code" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Codigo</label></h4>
                <input name="code" class="form-control" type="text" value="{{ $color->code }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Codigo del color</b></small>
                @error('code')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
             {{-- <div id="hexadecimal" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Valor Hexadecimal</label></h4>
                <input name="hexadecimal" class="form-control" type="text" value="{{ $color->hexadecimal }}">
                <small id="passwordHelpBlock" class="form-text text-muted"><b>Codigo del valor hexadecimal</b></small>
                @error('code')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div> --}}
            <div id="image" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Imagen</label></h4>
                <input name="image" class="form-control-file" type="file">
                @error('image')
                <div id="error" class="alert alert-danger mx-auto col-11 col-sm-4 col-lg-12"><span>{{ $message }}</span></div>
                @enderror
            </div>
            <div id="extras" class="form-group col-12 col-md-6 col-lg-3">
                <h4><label for="">Extras</label></h4>
                <div class="form-check">
                    @if ($color->season)
                    <input name="season" class="mt-1 mr-1" type="checkbox" checked value="si">
                    <label for="">Color de temporada</label>
                    @else
                    <input name="season" class="mt-1 mr-1" type="checkbox" value="si">
                    <label for="">Color de temporada</label>
                    @endif
                </div>
            </div>
        </div>
        <div id="buttons" class="text-center col-12">
            <button class="mx-2 btn btn-outline-dark" type="submit">Modificar</button>
            <a href="{{route('colors.index')}}"><button class="btn btn-outline-dark" type="button">Cancelar</button></a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/color/index.blade.php
@extends('layouts.app')
@section('content')
<div id="div-all-color" class="col-12">
    <div id="div-tit-color" class="mx-auto text-center col-2">
        <h2>Colores</h2>
        <a href="{{route('admin')}}" style="text-decoration: none; color:black"><i class="fas fa-arrow-circle-left"></i> Volver</a>
    </div>
    <div id="div-opc-color" class="row justify-content-center mx-auto mb-3 col-12 col-md-8 col-lg-6 col-xl-4">
        <div class="my-3 col-6 col-md-4">
            <a href="{{route('colors.create')}}"><button class="btn btn-outline-dark w-100">Nuevo</button></a>
        </div>
        <form class="input-group input-group-sm mb-5 my-auto col-12 col-md-6" action="{{route('colors.search')}}" method="post">
            @csrf
            <div class="input-group-prepend">
                <button class="input-group-text" id="inputGroup-sizing-sm">Buscar</button>
            </div>
            <input type="text" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
        </form>
    </div>
    <div class="my-2 col-12 text-center">
        @if(Session::has('notice'))
        <h3 class="my-auto text-success"><strong>{{ Session::get('notice') }}</strong></h3>
        @endif
    </div>
</div>
<div class="table" style="overflow-x:auto;">
    <table class="mx-auto">
        <thead>
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Categoria</th>
                <th scope="col">Temporada</th>
                <th scope="col">imagen</th>
                <th scope="col">Codigo</th>
                <th scope="col">Opciones</th>
            </tr>
        </thead>
        <tbody>
            @if(isset($colors))
            @foreach($colors as $color => $data)
            <tr class="text-center">
                <th scope="row">{{$data->id}}</th>
                <th>{{$data->category->name}}</th>
                @if ($data->season)
                <th class="text-center">Si</th>
                @else
                <th class="text-center">No</th>
                @endif
                <th class="w-25"><img class="col-1 w-100 rounded-circle p-0" id="{{ $data->id }}" src="{{asset('storage/'.$data->image)}}"></>
                <th>{{$data->code}}</th>
                <th>
                    <a href="{{route('colors.edit',['color'=>$data])}}">editar</a>
                    ||
                    <a href="{{route('colors.delete',['id'=>$data])}}">eliminar</a>
                </th>
            </tr>
            @endforeach
            @endif
        </tbody>
    </table>
</div>
@endsection